# Generated by Django 6.0.1 on 2026-02-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('actors', models.TextField(help_text='Comma-separated list of actors/actresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
